development:
  clients:
    default:
      uri: <%=ENV["MONGODB_URI"]%>
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true
      options:
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: home_tv_test
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%=ENV["MONGODB_URI"]%>
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true
      options:
  options:
    raise_not_found_error: false
