production:
  :concurrency: 1
staging:
  :concurrency: 1
development:
  :concurrency: 1
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

:schedule:
  fetch_scheduler:
    every: '10m'
    class: FetchScheduler
  reserve_scheduler:
    every: '60m'
    class: ReserveScheduler
  move_scheduler:
    every: '10m'
    class: MoveScheduler